# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16wuk-vHJevjVOczk8I05iiexWH_zgfu5
"""

import pandas as pd
df = pd.read_csv("Salary_dataset.csv")

print(f"Roes: {df. shape[0]}, columns: {df.shape[1]}")
print(f"column names: {list(df.columns)}")
df.head()

print("--- 2.1 Basic statistics ---")
display(df.describe())

print("---2.2 Data types---")
print(df.dtypes)

print("---2.3 Missing values per solumn----")
print(df.isna().sum())

print("--- 2.4 Duplicate rows ---")
print (f"Duplicate rows: {df.duplicated().sum()}")
print ("Duplicate rows: ")

print("--- 2.5 Unique values ---")
for col in df.columns:
  print(f"{col}: {df[col].nunique()}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

X = df[['YearsExperience']]
Y = df[['Salary']]

print('Feature shape:', X.shape)
print('Targer shape:', Y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

print('Training samples:', len(X_train))
print('Testing samples:', len(X_test))

y_train

X_train

from sklearn.impute import SimpleImputer

# Impute missing values in X_train and y_train
imputer_X = SimpleImputer(strategy='mean')
X_train_imputed = imputer_X.fit_transform(X_train)

imputer_y = SimpleImputer(strategy='mean')
y_train_imputed = imputer_y.fit_transform(y_train)

model = LinearRegression()

fitted_model = model.fit(X_train_imputed, y_train_imputed)

# Impute missing values in X_test using the imputer fitted on X_train
X_test_imputed = imputer_X.transform(X_test)

y_prediction = model.predict(X_test_imputed)
print('Predicted salary values:')
print(y_prediction)

plt.figure(figsize= (8, 5))
plt.scatter(X_train['YearsExperience'], y_train['Salary'], label='Training Data')

plt.title('salary vs Years of Experience - Train Date')
plt.xlabel('Years of Experience')
plt.ylabel('salary')
plt.legend()
plt.grid(True)
plt.show()

import pickle

filename = 'Salary_linear_regression_model.sav'
pickle.dump(model, open(filename, 'wb'))

print ('Model Saved as:', filename)

loaded_model = pickle.load(open('Salary_linear_regression_model.sav', 'rb'))

print('saved model loaded successfully.')

new_experience = 6.0

new_data = pd.DataFrame({'YearsExperience':[new_experience]})
predicted_Salary = loaded_model.predict(new_data.values)[0][0]

print(f'Years of Experience: {new_experience}')
print(f'Years of Salary: {predicted_Salary:.2f}')